const folderPath = './storageStates/';
export const TWOCENTS_LOGIN = folderPath + 'twocentsLogin.json';
export const TWOCENTS_LOGIN_VIEW = folderPath + 'twocentsLogin_View.json';
export const TWOCENTS_LOGIN_ONB = folderPath + 'twocentsLogin_Onb.json';
export const EMAIL_LOGIN = folderPath + 'gmailLogin.json';
export const EMAIL_LOGIN_VIEW = folderPath + 'gmailLoginView.json';
export const EMAIL_LOGIN_MSFT = folderPath + 'msftLogin.json';
export const EMAIL_LOGIN_ONB = folderPath + 'onbLogin.json';
export const EMPTY = folderPath + 'empty.json';
